### ISSUE TITLE
Conflicting information about grid licenses

### ISSUE THREAD

**Issue by kbevers** [icsm-au/transformation_grids#3]
Here on GitHub the license for the grids are clearly stated as CC BY 4.0, but on http://www.icsm.gov.au/gda/grids.html the same files are said to be licensed under BSD 3-Clause. From previous discussions I know that CC BY 4.0 is the correct license so the ICSM website should be updated to reflect that.

**Comment by alexgleith** [comment]
Thanks for pointing this out, @kbevers. I've contacted @tasgeodesist and he should be able to fix it.

**Comment by tasgeodesist** [comment]
ICSM website amended to say grids provided under CC BY 4.0 licence. Thanks @kbevers and @alexgleith

**Comment by dvdoug** [comment]
Hi

The "Geocentric Datum of Australia 2020 Technical Manual Version" also mentions that these files are under BSD (see page 35).

![image](https://user-images.githubusercontent.com/1571110/120702516-158e5300-c4ac-11eb-960d-6fa6097456af.png)

**Comment by dvdoug** [comment]
Also page 67
