### ISSUE TITLE
Grid files are too large for default distribution

### ISSUE THREAD

**Issue by nyalldawson** [icsm-au/transformation_grids#4]
The grid files here are very large, and unfortunately as a result they've been blocked from inclusion in the proj-datumgrid package. This means that the grid files are not available by default on important platforms such as the osgeo4w install (accordingly they are not available in a qgis install without manual user installation).

Is there any chance the grids could be thinned to avoid this situation?

Relevant discussion is at:

https://github.com/OSGeo/proj-datumgrid/issues/16#issuecomment-368336979

**Comment by sebastic** [comment]
Because of the large size, the proj-datumgrid-oceania archive will need to be packaged separately in Linux distributions and OSGeo4W.

**Comment by alexgleith** [comment]
Feedback I've received says that the grids should not, and will not be thinned.

Considering this and the fact that the grids will still be packaged in a way that is suitable for inclusion in software packages, I think we can close this. Thanks for bringing it to our attention, @nyalldawson.
