### ISSUE TITLE
GeoTools/jGridShift reports gsb files as invalid

### ISSUE THREAD

**Issue by aaime** [icsm-au/transformation_grids#6]
GeoTools uses the jGridShift library to read and apply NTv2 grid shift files. JGridShift is not happy with the contents of the files, and throws exceptions.

GeoTools uses an older version of of jGridShift (v1.0), but for reference, the source code is a lot like the latest one available here, where it's comparing the ``nodeCount`` with ``lonColumnCount`` times ``latRowCount`` and finds the two numbers are indeed different, hence throws an exception:
https://github.com/floscher/jGridShift/blob/master/src/main/java/au/com/objectix/jgridshift/NTv2SubGrid.java#L187

Trying to load the ``GDA94_GDA2020_conformal_and_distortion.gsb`` file the error message is:

> java.lang.IllegalStateException: SubGrid WEST_DC5 has inconsistent grid dimensions

For reference, lonColumnCount=1100, latRowCount=1481, nodeCount=1630581 , so there seems to be an excess of nodes? (1481×1100=1629100)

Upon trying to load the ``GDA94_GDA2020_conformal.gsb`` file, the jGridShift library throws the following error:
> java.lang.IllegalStateException: SubGrid WEST_C5 has inconsistent grid dimesions

The number of cols, rows and node counts is the same as in the other file.

**Comment by davecollett** [comment]
I believe it may be an inconsistency with the NTv2 file format - the GS_COUNT field in the header has an upper limit of 6 digits. (see page 54 of: https://www.dnrm.qld.gov.au/__data/assets/pdf_file/0006/105765/gday-21-user-guide.pdf)
I've found that if you comment out that nodeCount check, it should work. Obviously not ideal..

**Comment by aaime** [comment]
@davecollett thanks for following up. Hum, to ignore it I would have to fork jGridShift, apply a patch and rebuild it (not my library, just using it, unfortunately the link I provided is also for a fork, which also seems dead by now).

Reading the guide it seem to be referring to an error in production of the GDA94 grids:

> However it was apparent that NTv2 binary was not compiler dependent. The justification for having an Australian version of the binary is no longer valid and retaining it will lead to further confusion in
the future. Ultimately, the best option is to abandon this version and adopt the Canadian
implementation.

So if I understand correctly the situation, the same issue was reproduced in the GDA2020 grids?

**Comment by davecollett** [comment]
@aaime Yes, my understanding is that the new grids were produced to be consistent with the GDA94 grids..

**Comment by aaime** [comment]
I've tried removing the check, it would actually cause pretty visible transformation errors, up to 30cm.
Checking the issue, it turned out the code was computing one row/column less than available, removing the check resulted in items of the grid to be zero instead of the expected value.
Made the calculation more robust here: https://github.com/geosolutions-it/jgridshift/commit/c0c4dc5f75945d943c1dbec822f3622a8527d948
